on:
  repository_dispatch:
    types: [certora_run]

jobs:
  certora_run_integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        if: ${{ false }}
      - run: |
          curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL"
